#CC=powerpc-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lm -lrt -L. 

OBJ					= bin/bsd-x64
EXECUTABLE 			= bin/squeeze2upnp-bsd-x64

include Makefile

