CC=powerpc-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lgomp -lpthread -lm -lrt -ldl -L. 

OBJ					= bin/ppc
EXECUTABLE 			= bin/squeeze2upnp-ppc
EXECUTABLE_STATIC	= bin/squeeze2upnp-ppc-static

include Makefile

