CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lpthread -lm -lrt -L.

OBJ					= bin/x86
EXECUTABLE 			= bin/squeeze2upnp-x86
EXECUTABLE_STATIC 	= bin/squeeze2upnp-x86-static

include Makefile

