CC		=	armv6j-cross-linux-gnueabihf-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lm -lrt -ldl -L. 

# for LD debug -s

OBJ					= bin/armv6hf
EXECUTABLE 			= bin/squeeze2upnp-armv6hf
EXECUTABLE_STATIC 	= bin/squeeze2upnp-armv6hf-static

include Makefile

