CC	 	= aarch64-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lm -lrt -L. 

# for LD debug -s

OBJ					= bin/aarch64
EXECUTABLE 			= bin/squeeze2upnp-aarch64
EXECUTABLE_STATIC 	= bin/squeeze2upnp-aarch64-static

include Makefile

