CC=sparc-cross-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lm -lrt -ldl -lstdc++ -L.

OBJ					= bin/sparc
EXECUTABLE 			= bin/squeeze2upnp-sparc
EXECUTABLE_STATIC 	= bin/squeeze2upnp-sparc-static

include Makefile

